name: rojo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build .github/build.project.json -o Adonis2.0_Nightly_${{ steps.date.outputs.date }}.rbxm

      - uses: actions/upload-artifact@v2
        with:
          name: Adonis2.0_Nightly_${{ steps.date.outputs.date }}
          path: Adonis2.0_Nightly_${{ steps.date.outputs.date }}.rbxm

      - name: Send file nightly build to Discord channel
        uses: tsickert/discord-webhook@v3.0.0
        if: github.repository == 'Sceleratis/Adonis_2.0' && github.event_name == 'push'
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK }}
          filename: Adonis2.0_Nightly_${{ steps.date.outputs.date }}.rbxm
