name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: Roblox/setup-foreman@v1
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./src/MainModule ./src/Loader
